apiVersion: v1
kind: Secret
metadata:
  name: drupal-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: drupal
  MYSQL_USER: drupal
  MYSQL_PASSWORD: drupalpassword