GET  http://localhost:3000/user/name?name=john

###
GET  http://localhost:3000/user

###
GET  http://localhost:3000/user/1

###
POST  http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "name": "sample"
}