version: '3.7'



services:
   db:
      image: mysql:8.0
      container_name: appsDB
      volumes:
        - ./data:/var/lib/mysql
      restart: always
      ports:
       - '6603:3306'
      environment:
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: T0psecret!
        MYSQL_ROOT_PASSWORD: T0psecret!
        MYSQL_DATABASE: default_schema

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8890:80'
      environment:
        PMA_HOST: db

   drupal:
      image: jmariano/drupaldrush:9.12
      container_name: drupal912
      volumes:
        - ./drupal:/var/www/html
      ports:
        - 8080:80
      depends_on:
        - db
      links:
        - db