apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.database.name | quote }}
  MYSQL_USER: {{ .Values.database.user | quote }}
  MYSQL_PASSWORD: {{ .Values.database.password | quote }}