version: '3.7'



services:
   db:
      image: mariadb:10.11
      container_name: appsDB
      volumes:
        - ./data:/var/lib/mysql
        - ./dev/mariadb:/docker-entrypoint-initdb.d
      restart: always
      ports:
       - '6603:3306'
      environment:
        MARIADB_USER: dbuser
        MARIADB_PASSWORD: <password>
        MARIADB_ROOT_PASSWORD: <password>
        MARIADB_DATABASE: docker_database

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8890:80'
      environment:
        PMA_HOST: db

   drupal:
      image: drupal:10.2
      container_name: drupal102
      volumes:
        - ./drupal:/var/www/html
      ports:
        - 8080:80
      depends_on:
        - db
      links:
        - db