# Schema for the configuration files of the Site Announcement.
# Step 1
#config_entity creates a table if config_object it creates a structure of serialized data for the config table
#list of data types drupal/core/config/schema/core.data_types.schema.yml
mymodule.announcement.*:
  type: config_entity 
  label: 'Site announcement'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    message:
      type: text
      label: 'Text'
